name: "check broken links in wiki"
on:
  workflow_dispatch:
  # twice per month
  schedule:
    - cron: "0 14 1,15 * *"
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: ./checks/linkcheck/lychee.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload lychee report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          if-no-files-found: error
          path: ./checks/linkcheck/lychee*-report
      - name: upload filtered xmldump artifact
        uses: actions/upload-artifact@v4
        with:
          name: wikidump-filtered.xml
          if-no-files-found: error
          path: ./checks/linkcheck/workdir/wikidump-filtered.xml
          compression-level: 9
